#!/bin/bash


cat pw.txt | cleos wallet unlock

cleos create account eosio seller EOS5EUcX6pBvNwgcvFjatgBR9uTvobpz9AxaZJrveD6kYzsJ6nZjS
cleos create account eosio buyer EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
cleos create account eosio intermed EOS7YmdcJwNtKBVgAqxDtij36paHBzPSXXQU1Fyd2Sygmi7QnYGb2
cleos create account eosio random EOS8EXyGVLjxTPyaZyEqJDzthx1SPNec3g13MgcYbNQTLv9KC5wkL